# Array Shape

* The shape of an array is a tuple of integers that indicates the number of elements along each dimension.

* Dimensionality :
* A 1D array has shape (n,) where n is the number of elements.
* A 2D array has shape (rows, columns).
* A 3D array has shape (depth, rows, columns).

# 1D array

In [5]:
import numpy as np
a = np.array([1, 2, 3])
print(a.shape)


(3,)


# 2D array

In [8]:
b = np.array([[1, 2], [3, 4], [5, 6]])
print(b.shape)

(3, 2)


# 3D array

In [11]:
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(c.shape) 

(2, 2, 2)


# Checking dimensionality 

*  .ndim: Returns the number of dimensions (axes) in the array.

In [17]:
print(b.ndim)
  




2


In [19]:
print(c.ndim)  

3


# Reshaping

* Reshaping changes the dimensions of an array while keeping the total number of elements the same.

# Reshape 1D array to 2D





In [30]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape(2, 3)
print(b)

[[1 2 3]
 [4 5 6]]


# Reshape to 3D array

In [32]:
c = a.reshape(2, 1, 3)
print(c)

[[[1 2 3]]

 [[4 5 6]]]


# Automatic dimension inference

In [25]:
d = a.reshape(3, -1)  
print(d)

[[1]
 [2]
 [3]]


# Flattening arrays

* Flattening converts a multi-dimensional array into a 1D array.

*  .flatten(): Returns a flattened copy of the array.

# Flattening a 2D array


In [37]:
b = np.array([[1, 2, 3], [4, 5, 6]])
flat = b.flatten()
print(flat) 

[1 2 3 4 5 6]


# Trasposing arrays


* Transposing changes the order of the axes in a multi-dimensional array.

* .transpose() or .T: Reverses the axes (e.g., rows become columns).

In [43]:

import numpy as np

# making a 3x3 array
a = np.array([[1, 2, 3],
				[4, 5, 6],
				[7, 8, 9]])

# before transpose
print(a, end ='\n\n')

# after transpose
print(a.transpose())


[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]


# Concatenating 

* Combines arrays along a specified axis.

# np.concatenate()

* The np.concatenate() is the main function for joining arrays in NumPy. It takes a sequence of arrays as input and concatenates them along the specified axis.

In [49]:
import numpy as np

arr1=np.array([[3,8,4,6],[8,7,6,2]])
arr2=np.array([[4,2,2,1],[6,4,3,1]])

print("Join two arrays along rows :")
joint_arr1=np.concatenate((arr1,arr2), axis=0)
print(joint_arr1)

print("Join two arrays along columns :")
joint_arr2=np.concatenate((arr1,arr2), axis=1)
print(joint_arr2)

Join two arrays along rows :
[[3 8 4 6]
 [8 7 6 2]
 [4 2 2 1]
 [6 4 3 1]]
Join two arrays along columns :
[[3 8 4 6 4 2 2 1]
 [8 7 6 2 6 4 3 1]]


# np.vstack()

* Stacks arrays vertically, meaning it appends arrays along the rows (axis 0).

In [53]:
import numpy as np


array3 = np.array([[7], [8]])
array4 = np.array([[9], [10]])
 

concatenated_vertical = np.vstack((array3, array4))
 
print("Array 3:")
print(array3)
 
print("\nArray 4:")
print(array4)
 
print("\nConcatenated Vertically:")
print(concatenated_vertical)

Array 3:
[[7]
 [8]]

Array 4:
[[ 9]
 [10]]

Concatenated Vertically:
[[ 7]
 [ 8]
 [ 9]
 [10]]


# np.hstack()

* Stacks arrays horizontally, meaning it appends arrays along the columns (axis 1).

In [58]:
import numpy as np


array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])


concatenated_horizontal = np.hstack((array1, array2))

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nConcatenated Horizontally:")
print(concatenated_horizontal)

Array 1:
[[1 2]
 [3 4]]

Array 2:
[[5 6]
 [7 8]]

Concatenated Horizontally:
[[1 2 5 6]
 [3 4 7 8]]


# Splitting

* Splitting arrays in NumPy involves dividing a single array into multiple sub-arrays.

# np.split()

In [63]:
import numpy as np


arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

split_arr = np.split(arr, 3)

print(split_arr)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
