# Array manipulation

* Array manipulation refers to changing the structure, dimensions, or content of NumPy arrays to suit specific needs.

# Multidimensional array

* A multi-dimensional array (ndarray) has multiple axes (dimensions):

* A 1D array is like a list: [1, 2, 3]
* A 2D array is like a matrix: [[1, 2, 3], [4, 5, 6]]
* A 3D array is like a cube: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

# Indexing in multidimensional array

* Indexing is the process of accessing a specific element in the array using its indices.

In [10]:
# Indexing in 2D array
import numpy as np
arr_2d = np.array([[1, 2, 3], 
                    [4, 5, 6], 
                    [7, 8, 9]])
print(arr_2d[1, 2]) 
print(arr_2d[0, -1]) 


6
3


In [12]:
# Indexing in a 3D Array
import numpy as np
arr_3d = np.array([[[1, 2], [3, 4]], 
                    [[5, 6], [7, 8]]])
print(arr_3d[1, 0, 1])  
print(arr_3d[0, 1, 0]) 

6
3


# Slicing in multidimensional array

In [17]:
# slicing in 2D array
import numpy as np
arr_2d = np.array([[1, 2, 3], 
                    [4, 5, 6], 
                    [7, 8, 9]])
print(arr_2d[:2, :])  


[[1 2 3]
 [4 5 6]]


In [19]:
# slicing in 3D array
print(arr_3d[:, 1, :])  

[[3 4]
 [7 8]]


# Masking (Logical Indexing Based on Conditions)

* Masking allows selecting elements based on conditions.

In [23]:
import numpy as np
 
a = np.array([1, 2, 3, 4, 5])
mask = a > 3
print(mask)

[False False False  True  True]


In [25]:
arr_2d = np.array([[10, 20, 30], 
                    [40, 50, 60], 
                    [70, 80, 90]])

mask = arr_2d > 40
print(arr_2d[mask])  



[50 60 70 80 90]


# Fancy Indexing (Selecting Elements Using Lists/Arrays)

* Fancy indexing allows selecting multiple elements using arrays of indices.

In [29]:
import numpy as np

array1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# select a single element
simple_indexing = array1[3]

print("Simple Indexing:",simple_indexing)   

# select multiple elements
fancy_indexing = array1[[1, 2, 5, 7]]

print("Fancy Indexing:",fancy_indexing)  

Simple Indexing: 4
Fancy Indexing: [2 3 6 8]
