# Arithmatic Operations on Numpy arrays

* Arithmetic operations in NumPy are applied element-wise, which means they are performed on each element of the array independently.

# Addition

In [5]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


# Substrction

In [8]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a-b)

[-3 -3 -3]


# Multiplication

In [11]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a*b)

[ 4 10 18]


# Division

In [14]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a/b)

[0.25 0.4  0.5 ]


# Broadcasting

* Broadcasting allows NumPy to perform operations between arrays of different shapes by expanding the smaller array to match the dimensions of the larger one.

# Rules of Broadcasting

* Arrays are aligned by their trailing dimensions (starting from the right).
* A dimension with size 1 or missing in one array can be stretched to match the corresponding dimension of the other array.

# Array with shape (3,)




In [24]:
import numpy as np
a = np.array([1, 2, 3])

# Scalar broadcasted to (3,)

In [26]:
import numpy as np
print(a + 5)  

[6 7 8]


# Broadcasting with a 2D array

In [28]:
import numpy as np
b = np.array([[1], [2], [3]])  
print(a + b)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


# Element wise operations and functions

* These operations apply a function to each element in the array.

In [37]:
import numpy as np
a = np.array([1, 4, 9, 16])




# Square root

In [39]:
print(np.sqrt(a))

[1. 2. 3. 4.]


# Exponential

In [41]:
print(np.exp(a))

[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]


# Trigonometric functions

In [43]:
angles = np.array([0, np.pi / 2, np.pi])
print(np.sin(angles))  
print(np.cos(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
