# Arrays in Numpy

# nd arrray (N-dimensional array )

* Core object in NumPy is the ndarray, representing N-dimensional arrays.
* Arrays are more efficient than Python lists due to contiguous memory allocation.

# Creating arrays

* np.arrays() : From a python list or tuple.

In [1]:
import numpy as np
a = np.array([1, 2, 3])

# np.zeros()

* np.zeros() : arrays filled with zeros.

In [25]:
arr_zeros = np.zeros(10)
print(arr_zeros)




[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


# np.ones()

* np.ones() : Array filled with ones.

In [27]:
arr_ones = np.ones(10)
print(arr_ones)



[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


# np.arange()

* Creates an array with evenly spaced values within a given range.

In [29]:
arr_range = np.arange(10)
print(arr_range)



[0 1 2 3 4 5 6 7 8 9]


# np.linspace()

* Creates an array with evenly spaced numbers over a specified interval.

In [ ]:
# Creating 5 Evenly Spaced Numbers Between 1 and 10

In [31]:
arr_linspace = np.linspace(1, 10, 5)
print(arr_linspace)



[ 1.    3.25  5.5   7.75 10.  ]


# Array indexing and slicing :

* NumPy allows powerful indexing and slicing to access and modify array elements.

 # Indexing (Accessing Elements)

In [4]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])  
print(arr[-1])  


10
50


In [ ]:
# For multidimensional arrays

In [11]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d[0, 1])  # Row 0, Column 1


2


# Slicing (Extracting Subarrays)

* Slicing follows the start:stop:step pattern.

In [6]:
arr = np.array([10, 20, 30, 40, 50, 60])
print(arr[1:4])  # Elements from index 1 to 3 (20, 30, 40)
print(arr[:3])   # First three elements
print(arr[::2])  # Every second element


[20 30 40]
[10 20 30]
[10 30 50]


In [ ]:
# For multidimensional arrays

In [9]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[:, 1])  # Second column
print(arr_2d[1:, :2])  # Bottom two rows, first two columns


[2 5 8]
[[4 5]
 [7 8]]
