# Broadcasting

* Broadcasting simplifies mathematical operations on arrays with different shapes. 
* It enables NumPy to efficiently apply operations element-wise without explicitly copying or reshaping data.

# Broadcasting Array in Single Value and 1D Addition

In [4]:
import numpy as np
arr = np.array([1, 2, 3])

res = arr + 1  # Adds 1 to each element
print(res)

[2 3 4]


# Broadcasting Array in 1D and 2D Addition

In [7]:
import numpy as np

# Broadcasting a 1D array with a 2D array
a1 = np.array([2, 4, 6])
a2 = np.array([[1, 3, 5], [7, 9, 11]])
res = a1 + a2
print(res)

[[ 3  7 11]
 [ 9 13 17]]


# Rules of broadcasting

* If the arrays have different shapes, NumPy aligns them right-aligned, meaning it compares dimensions from the last axis backward.
* If a dimension of size 1 is matched with a larger dimension, the smaller array is stretched (virtually copied) along that dimension.
* Two dimensions are compatible when:
      They are equal, or
      One of them is 1 (broadcasting expands the smaller dimension).


# Broadcasting along axes :

In [15]:
row_vec = np.array([[1, 2, 3]])  # Shape (1,3)
col_vec = np.array([[1], [2], [3]])  # Shape (3,1)

result = row_vec + col_vec
print(result)


[[2 3 4]
 [3 4 5]
 [4 5 6]]


# Broadcasting  matching dimensions :


In [20]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])  # Shape (3,3)

B = np.array([1, 2, 3])  # Shape (3,)

result = A + B
print(result)


[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
