# Mathematical function :

# Universal Function :

* Universal functions are NumPy's element-wise functions. They operate on each element of an array independently and support broadcasting.

* np.add(x, y) → Element-wise addition.
* np.subtract(x, y) → Element-wise subtraction.
* np.multiply(x, y) → Element-wise multiplication.
* np.divide(x, y) → Element-wise division.

# np.add(x,y) :

In [6]:
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)
print(z)


[ 5  7  9 11]


# np.substract(x,y) :

In [13]:
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.subtract(x, y) 
print(z)


[-3 -3 -3 -3]


# np.multiplication(x,y)

In [16]:
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.multiply(x, y)  
print(z)


[ 4 10 18 28]


# np.divide(x,y)

In [19]:
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.divide(x, y)  
print(z)


[0.25       0.4        0.5        0.57142857]


# Statistical function :

# np.mean () :

* Computes the arithmetic mean (average) of the elements in the array.

In [24]:
import numpy as np
data = np.array([1, 2, 3, 4, 5])
mean_value = np.mean(data)
print("Mean:", mean_value) 


Mean: 3.0


# np.median() :

* Computes the median (middle value) of the elements in the array.

In [30]:
import numpy as np
data = np.array([1, 2, 3, 4, 5])
median_value = np.median(data)
print("Median:", median_value) 


Median: 3.0


# np.std() :

* Computes the standard deviation, a measure of how spread out the data is.

In [34]:
data = np.array([1, 2, 3, 4, 5])
std_value = np.std(data)
print("Standard Deviation:", std_value)


Standard Deviation: 1.4142135623730951


# np.var() :

* Computes the variance, which is the square of the standard deviation. It measures the average squared deviation from the mean.

In [38]:
data = np.array([1, 2, 3, 4, 5])
variance_value = np.var(data)
print("Variance:", variance_value)


Variance: 2.0


# np.min() :

* Returns the smallest element in the array.

In [42]:
import numpy as np
data = np.array([10, 20, 30, 40, 50])
minimum_value=np.min(data)
print("Minimum:",minimum_value)

Minimum: 10


# np.max() :

* Returns the largest element in the array.

In [45]:
import numpy as np
data = np.array([10, 20, 30, 40, 50])
maximum_value=np.max(data)
print("Maximum:",maximum_value)

Maximum: 50


# Linear algebra function :

# np.dot() :

* Computes the dot product of two arrays.

# Dot product of 1-D arrays :

In [52]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_1d = np.dot(a, b)
print("Dot product of 1D arrays:", dot_1d)

Dot product of 1D arrays: 32


# np.matmul() :

* Performs matrix multiplication. Unlike np.dot(), it doesn’t handle the scalar dot product for 1D arrays.

# 2D arrays matrix multiplication :

In [58]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

matmul_result = np.matmul(A, B)
print("Matrix Multiplication (matmul):\n", matmul_result)

Matrix Multiplication (matmul):
 [[19 22]
 [43 50]]


# np.linalg.inv() :

* Computes the inverse of a square matrix.

In [63]:
matrix = np.array([[4, 7], 
                   [2, 6]])
inverse_matrix = np.linalg.inv(matrix)
print("Inverse of the matrix:\n", inverse_matrix)

Inverse of the matrix:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


# np.linalg.eig() :

* Computes the eigenvalues and eigenvectors of a square matrix.

In [67]:

matrix = np.array([[4, -2], 
                   [1, 1]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)



Eigenvalues: [3. 2.]
Eigenvectors:
 [[0.89442719 0.70710678]
 [0.4472136  0.70710678]]
